### ISSUE TITLE
Build fails in JIT mode.

### ISSUE THREAD

**Issue by christianmagill** [stormwarning/tailwindcss-capsize#99]
I love the idea for this plugin but unfortunately it throws errors during build in JIT mode.

```
ERROR in ./resources/styles/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: plugin is not a function
    at registerPlugins (/Users/christianmagill/Code/Sites/site/wp-content/themes/site/node_modules/tailwindcss/lib/jit/lib/setupContextUtils.js:540:7)
    at createContext (/Users/christianmagill/Code/Sites/site/wp-content/themes/site/node_modules/tailwindcss/lib/jit/lib/setupContextUtils.js:583:3)
    at getContext (/Users/christianmagill/Code/Sites/site/wp-content/themes/site/node_modules/tailwindcss/lib/jit/lib/setupContextUtils.js:644:17)
    at /Users/christianmagill/Code/Sites/site/wp-content/themes/site/node_modules/tailwindcss/lib/jit/lib/setupTrackingContext.js:177:57
    at /Users/christianmagill/Code/Sites/site/wp-content/themes/site/node_modules/tailwindcss/lib/jit/processTailwindFeatures.js:54:7
    at /Users/christianmagill/Code/Sites/site/wp-content/themes/site/node_modules/tailwindcss/lib/jit/index.js:25:56
    at LazyResult.runOnRoot (/Users/christianmagill/Code/Sites/site/wp-content/themes/site/node_modules/postcss/lib/lazy-result.js:333:16)
    at LazyResult.runAsync (/Users/christianmagill/Code/Sites/site/wp-content/themes/site/node_modules/postcss/lib/lazy-result.js:385:26)
    at LazyResult.async (/Users/christianmagill/Code/Sites/site/wp-content/themes/site/node_modules/postcss/lib/lazy-result.js:215:30)
    at LazyResult.then (/Users/christianmagill/Code/Sites/site/wp-content/themes/site/node_modules/postcss/lib/lazy-result.js:200:17)
    at processResult (/Users/christianmagill/Code/Sites/site/wp-content/themes/site/node_modules/webpack/lib/NormalModule.js:700:19)
    at /Users/christianmagill/Code/Sites/site/wp-content/themes/site/node_modules/webpack/lib/NormalModule.js:806:5
    at /Users/christianmagill/Code/Sites/site/wp-content/themes/site/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /Users/christianmagill/Code/Sites/site/wp-content/themes/site/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/Users/christianmagill/Code/Sites/site/wp-content/themes/site/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.loader (/Users/christianmagill/Code/Sites/site/wp-content/themes/site/node_modules/postcss-loader/dist/index.js:96:7)

```

Here's my config... If I remove Capsize compilation works.

```
module.exports = {
  // mode: 'jit',
  purge: {
    content: [
      './app/**/*.php',
      './resources/**/*.{php,vue,js}',
    ],
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    fontFamily: {
      sans: ['Inter', 'sans-serif'],
    },
    fontMetrics: {
      sans: {
        capHeight: 2048,
        ascent: 2728,
        descent: -680,
        lineGap: 0,
        unitsPerEm: 2816,
      },
    },
    aspectRatio: {
      none: 0,
      square: [1, 1],
      "16/9": [16, 9],
      "4/3": [4, 3],
      "21/9": [21, 9],
    },
    extend: {
      colors: {},
    },
  },
  variants: {
    aspectRatio: ['responsive'],
    extend: {},
  },
  plugins: [
    // require('@tailwindcss/typography'),
    // require('@tailwindcss/aspect-ratio'), // https://github.com/tailwindlabs/tailwindcss-aspect-ratio
    // require('tailwindcss-skip-link')(), // https://github.com/opdavies/tailwindcss-plugin-skip-link
    // require('tailwindcss-debug-screens'), // https://github.com/jorenvanhee/tailwindcss-debug-screens
    // require('tailwindcss-elevation')(['responsive']), // https://github.com/jonaskay/tailwindcss-elevation
    // require('@tailwindcss/line-clamp'), // https://github.com/tailwindlabs/tailwindcss-line-clamp
    require('tailwindcss-capsize'), // https://github.com/stormwarning/tailwindcss-capsize
  ],
};


```

**Comment by stormwarning** [comment]
I think I need to fix how the plugin is exported after building from TypeScript — does `require('tailwindcss-capsize').default` work?

**Comment by christianmagill** [comment]
That fixed it! Thanks for the response.

**Comment by stormwarning** [comment]
Great! I should have a new version out in a couple days and I will hopefully have a fix for that included with it 👍

**Comment by christianmagill** [comment]
Awesome! Much thanks
